export const colors = {
  bg: '#FAFAFA',
  surface: '#FFFFFF',
  text: '#1A1A1A',
  textMuted: '#6B6B6B',
  given: '#1A1A1A',
  filled: '#1E5BD8',
  cellBorder: '#C8C8C8',
  cellBoxBorder: '#1A1A1A',
  cellSelected: '#3F8AE0',
  cellPeer: '#DCEAFB',
  cellMatch: '#FFE9A8',
  cellConflict: '#F4B5B5',
  cellConflictText: '#9B1414',
  primary: '#1E5BD8',
  primaryText: '#FFFFFF',
  danger: '#C43A3A',
  shadow: 'rgba(0,0,0,0.08)',
};
